### ISSUE TITLE
Version 0.0.3 broke esdoc

### ISSUE THREAD

**Issue by fmonniot** [esdoc/esdoc-es7-plugin#4]
Hi!

I just installed the new version of this plugin (0.0.3) and, when running esdoc, I get the following error.
I use node v4.1.1 and npm v3.3.7.

```
/Users/fmonniot/project/node_modules/esdoc/out/src/ESDoc.js:409
            throw _iteratorError5;
            ^
Error: Unknown node type SpreadProperty.
    at Controller.traverse (/Users/fmonniot/project/node_modules/estraverse/estraverse.js:515:31)
    at Object.traverse (/Users/fmonniot/project/node_modules/estraverse/estraverse.js:707:27)
    at Function.traverse (/Users/fmonniot/project/node_modules/esdoc/out/src/Util/ASTUtil.js:55:31)
    at Function._traverse (/Users/fmonniot/project/node_modules/esdoc/out/src/ESDoc.js:441:34)
    at /Users/fmonniot/project/node_modules/esdoc/out/src/ESDoc.js:187:26
    at Function._walk (/Users/fmonniot/project/node_modules/esdoc/out/src/ESDoc.js:394:13)
    at Function._walk (/Users/fmonniot/project/node_modules/esdoc/out/src/ESDoc.js:396:18)
    at Function._walk (/Users/fmonniot/project/node_modules/esdoc/out/src/ESDoc.js:396:18)
    at Function.generate (/Users/fmonniot/project/node_modules/esdoc/out/src/ESDoc.js:127:12)
    at ESDocCLI.exec (/Users/fmonniot/project/node_modules/esdoc/out/src/ESDocCLI.js:90:28)
```

Thanks for your work on esdoc !

**Comment by h13i32maru** [comment]
@fmonniot Hi! Thanks for this issue! 
I am using npm v2.14.4. Please try workaround with the npm.
And I want to completely fix this problem in future version.

**Comment by h13i32maru** [comment]
Sorry, I was mistake for problem reason. Now, I published ESDoc v0.4.3. Please try again.

```
npm uninstall esdoc esdoc-es7-plugin
npm install esdoc esdoc-es7-plugin
esdoc -c esdoc.json
```

**Comment by fmonniot** [comment]
It workings with esdoc 0.4.3. Maybe it'll be best to indicates in this repo readme that this version of esdoc is required ?
Thank you for your reactivity !

**Comment by h13i32maru** [comment]
This plugin is out-of-date. Please check [using ECMAScript Proposal](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
