### ISSUE TITLE
SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by benadamstyles** [esdoc/esdoc-es7-plugin#6]
Sorry for the rather pathetic plea but does anyone know any way to debug this? Or perhaps it is a bug with this plugin? The only `u` in the code snippet are in lines 169, 170 and 177, and none of them are syntax errors.

Thanks for any help anyone can give.

```
error: could not process the following code.
/Users/ben/Dev/Git/.../assets/js/entries/dashboard.js
167|         // Call link's method
168|         model[
169|           $(`option[value=${chosenTab}]`)
170|           .getAttribute('data-onclick')
171|         ]()
172|       }
173|     }
174|   })()
175| )
176|
177| grab = async function grab(tabName, from = 0) { // NOTE babel bug

/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/ESDoc.js:415
            throw _iteratorError5;
            ^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at DocFactory._copy (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/Factory/DocFactory.js:978:19)
    at DocFactory._decideExpressionStatementType (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/Factory/DocFactory.js:806:27)
    at DocFactory._decideType (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/Factory/DocFactory.js:700:23)
    at DocFactory._createDoc (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/Factory/DocFactory.js:602:25)
    at DocFactory._traverseComments (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/Factory/DocFactory.js:565:24)
    at DocFactory.push (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/Factory/DocFactory.js:451:22)
    at Controller.<anonymous> (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/ESDoc.js:449:19)
    at Controller.enter (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/out/src/Util/ASTUtil.js:57:20)
    at Controller.__execute (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/ben/Dev/Git/HireHubStatic/node_modules/esdoc/node_modules/estraverse/estraverse.js:495:28)
```

**Comment by nebulou5** [comment]
I'm having a similarly cryptic error message.

```
node_modules/esdoc/out/src/ESDoc.js:409
            throw _iteratorError5;
            ^
```

> TypeError: Cannot read property 'name' of undefined

error: could not process the following code.

```
-1| undefined
0| import _ from 'lodash';
1| import * as actionTypes from '../../actionTypeConstants';
2|
3| function getResults({items, ...state}, isVisible) {
```

**Comment by h13i32maru** [comment]
Sorry for late reply.
This plugin is out-of-date. Please check [using ECMAScript Proposal](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
